Add recycler on homescreen
brshpl/krokodil pull request #3
Opened 2020-04-26 21:50 UTC by Syelkonya

2020-04-26 23:40 UTC, maksimuimin requested changes
Вроде норм, фиксы описал. Единственное, я так и не понял, что у вас происходит с LobbyList. Он как-то через всю архитектуру хитро прокидывается, а где используется я так и не увидел

2020-04-26 23:40 UTC, maksimuimin commented on app/src/main/AndroidManifest.xml
> +                <category android:name="android.intent.category.LAUNCHER" />
Нужно спилить, у вас вроде LoginActivity теперь первой запускается

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/data/model/Lobby.java
> +    }
В чём сакральный смысл данного кода?) Ты объявляешь 5 приватных полей и для каждого из них объявляешь геттер и сеттер. Нет принципиальной разницы с 5-ю публичными полями, всё равно всё доступно и на чтение, и на запись. Насколько я понимаю, у вас Lobby - это объект-значение (вы получаете его из базы и больше не меняете) В таком случае, вам не нужны сеттеры. Если я не прав и сеттеры нужны, тогда почему сеттеры, а не публичные поля? Такое имеет смысл только если делать какие-нибудь валидации или обработку данных в сеттере

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/utils/BindingAdapters.java
> +    }
А. где это используется? В твоём диффе не могу найти

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/utils/BindingAdapters.java
> +
Давай аккуратнее писать, лишние пустые строки тут не нужны, одной достаточно

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/utils/BitmapUtils.java
> +        return Bitmap.createBitmap(bitmap, cropW, cropH, newWidth, newHeight);
Странная логика, без 100 грамм не разберёшься. К любой математике обязательно пишем комментарий. Ну и, например, твои height - ( height -width) в тернарном операторе прямо явно равны width. Тернарный оператор в принципе спорная штука. Вообще, я не запрещаю его использовать, но в некоторых современных языках его специально не реализуют, чтобы не усложнять код. Так что, использовать с осторожностью. Если выражение сложное, лучше написать обычный условный оператор

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/utils/BitmapUtils.java
> +    public RoundedBitmapDrawable createRoundedBitmapDrawableWithBorder(Bitmap bitmap, Resources resources){
Тоже странная функция. На сколько я понимаю, здесь рисуется что-то типа аватарки (с рамкой?) через битмапы. Такое лучше делать через разметку: получишь результат быстрее и код проще. Если работает, можно, наверное, оставить пока, но я бы прямо сильно задумался о тот, чтобы переписать это, если я правильно понял идею функции

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/view/HomeScreenFragment.java
> +//        mLobbyAdapter = new LobbyAdapter(list, getContext());
Закомментированный код мёрджить плохо

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/view/HomeScreenFragment.java
> +        Lobby lobby123 = new Lobby();
Так себе название

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/viewmodel/HomeScreenViewModel.java
> +}
Что тут будет? Если есть заготовки кода, который ещё не написан пишите комментарии вида //TODO somthing

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/java/com/krokoteam/kroko/viewmodel/LobbyListItemViewModel.java
> +    }
В чём смысл? Аналогично, см. коммент выше

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/res/layout/fragment_create_lobby.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
Лишний лейаут. У тебя всё внутри FrameLayout лежит, поставь его корневым

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/res/layout/fragment_home_screen.xml
> +    <!--</LinearLayout>-->
Чистим закомментированный код

2020-04-26 23:40 UTC, DragonF0rm commented on app/src/main/res/values/colors.xml
> +    <color name="colorGrayTit">#CCCCCC</color>
Полегче с цветами) Во-первых, цвета лучше называть по назначению, а не по, собственно, цвету. Во-вторых, в матириал гайдлайне используется не так много цветов. Я не видел, что у ва за UI, но вам точно столько нужно?

2020-04-27 13:27 UTC, Syelkonya commented on app/src/main/res/layout/fragment_create_lobby.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
Иначе databinding не будет работать

2020-04-27 16:20 UTC, merged

2020-04-28 10:39 UTC, DragonF0rm commented on app/src/main/res/layout/fragment_create_lobby.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
Ок, посмотрел, оставляем